const CONFIG = {
    titleWeb: "Web sieu xin xo con bo cua Vinh",
    introTitle: 'Mon',
    introDesc: `hihihi`,
    btnIntro: '^^HiHi^^',
    title: ':)))',
    desc: 'Web on ko?',
    btnYes: 'chap nhan dc,
    btnNo: 'Không nha :3',
    question: 'ko cco content nen ghi bua <3',
    btnReply: 'kkk',
    reply: '<b>???</b>',
    mess: '<b><color=#F3F>/???</a><color=#F33>???</a></b>',
    messDesc: '...',
    btnAccept: 'System error/ <3',
    messLink: 'https://github.com/zukahai/Confess-Crush'   //https://www.facebook.com/vinh.truonggia.355
